# config.yaml grpctest
db:
  path: database
  kind: sqlite3
  name: testdb
queue:
  txs_limits: 2000
  block_limits: 30
cache:
  client_limits: 500
  tx_list_limits: 100
commit:
  wait_interval: 1000
  num_tx_in_block: 99
peer:
  id: peer3@peer
  public_key: b3918c70db7e308d6b686c01ab0e08f3f677066eb8aba72c33f22b2798799635
  private_key: 6fd47967cc1389e7e0c7838f35a8d5d42277a931c072251f7478a2544592c21db3918c70db7e308d6b686c01ab0e08f3f677066eb8aba72c33f22b2798799635
  host: 192.168.100.3
  port: 50055
  active: false
sync:
  from:
    id: "root@peer"
    public_key: 3788ef7f97cbc4bda223add5ea147fa3e8a096ad4f27b0dcf247e9fb9443060e
    host: 192.168.100.3
    port: 50052
  limits: 50
prosl:
  id: "/prosl"
  genesis:
    path: example/genesis.yaml
  incentive:
    path: example/incentive.yaml
    id: incentive/prosl
  consensus:
    path: example/consensus.yaml
    id: consensus/prosl
  update:
    path: example/update.yaml
    id: update/prosl
root:
  id: root@root
