# config.yaml default
db:
  path: database
  kind: sqlite3
  name: db
queue:
  txs_limits: 1000
  block_limits: 30
cache:
  client_limits: 500
  tx_list_limits: 100
commit:
  wait_interval: 1000
  num_tx_in_block: 1000
peer:
  id: root@peer
  public_key: 3788ef7f97cbc4bda223add5ea147fa3e8a096ad4f27b0dcf247e9fb9443060e
  private_key: 82d2750b9278d74cd492ba21ba5843655123f903f7fdadb654f6519bf1f9dea73788ef7f97cbc4bda223add5ea147fa3e8a096ad4f27b0dcf247e9fb9443060e
  host: 127.0.0.1
  port: 50023
  active: true
sync:
  to: "root@pr"
  limits: 50
prosl:
  id: "/prosl"
  genesis:
    path: ./grpc_test/genesis.yaml
  incentive:
    path: ./grpc_test/incentive.yaml
    id: incentive/prosl
  consensus:
    path: ./grpc_test/consensus.yaml
    id: consensus/prosl
  update:
    path: ./grpc_test/update.yaml
    id: update/prosl
root:
  id: root@com