# config.yaml default
db:
 path: database
 kind: sqlite3
 name: db
proposal_txs_limits: 1000
commit:
 num_tx_in_block: 1000
peer:
 public_key: 0
 private_key: 0
 port: 50023
incentive:
 default: incentive.yaml
 path: incentive/prosl
consensus:
 default: consensus.yaml
 id: consensus/prosl
change_rule:
 default: rule.yaml
 id: rule/prosl
