# config.yaml grpctest
db:
  path: database
  kind: sqlite3
  name: testdb
proposal_txs_limits: 1000
commit:
  wait_interval: 1000
  num_tx_in_block: 99
peer:
  id: root@peer
  public_key: 3788ef7f97cbc4bda223add5ea147fa3e8a096ad4f27b0dcf247e9fb9443060e
  private_key: 82d2750b9278d74cd492ba21ba5843655123f903f7fdadb654f6519bf1f9dea73788ef7f97cbc4bda223add5ea147fa3e8a096ad4f27b0dcf247e9fb9443060e
  port: 50023
prosl:
  id: "/prosl"
  genesis:
    path: genesis.yaml
  incentive:
    path: incentive.yaml
    id: incentive/prosl
  consensus:
    path: consensus.yaml
    id: consensus/prosl
  update:
    path: update.yaml
    id: update/prosl
root:
  id: root@root